version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file cflambdatemplate.yml --s3-bucket photo-lambda-pipeline-bucket --output-template-file lambda-output-template.yml
artifacts:
  files:
    - lambda-output-template.yml