AWSTemplateFormatVersion: "2010-09-09"
Description: "LambdaCloudFormationTemplate"
Resources:
#LAMBDA
  LambdaFunction1CF: #Lambda Function-Index Photos
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: indexphotos-lambda-function-1-cf
      Runtime: python3.9
      CodeUri: ./search_photos
        # ZipFile: #need to add the code here
        #   "exports.handler = function(event, context){\n
        #     var sample = sample;"
      Role: arn:aws:iam::927015531901:role/lambda-index-photos
        # Fn::GetAtt:
          # - IndexPhotosLambdaExecutionRole
          # - Arn
  LambdaFunction2CF: #Lambda Function-Search Photos
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: searchphotos-lambda-function-2-cf
      Runtime: python3.9
      CodeUri: ./index_photos
        # ZipFile: #need to add the code here
        #   "exports.handler = function(event, context){\n
        #     var sample = sample;"
      Role: arn:aws:iam::927015531901:role/service-role/search-photos-role-u9e4q58p
        # Fn::GetAtt:
        #   - SearchPhotosLambdaExecutionRole
        #   - Arn
  # Permission to call L2