AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos-lf2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ../../lambda_functions/search_photos
      Description: 'Lambda function for smart-photos-album searching photos'
      MemorySize: 128
      Timeout: 180
      Role: 'arn:aws:iam::517397763736:role/service-role/search_photos-role-vrozly1e'
      Environment:
        Variables:
          REGION: us-west-2

  indexPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-lf1
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ../../lambda_functions/index_photos
      Description: 'Lambda function for smart-photos-album indexing photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::517397763736:role/lambda_photos_rekognition'
      Environment:
        Variables:
          REGION: us-west-2
    Bucket1:
      Type: 'AWS::S3::Bucket'